### ISSUE TITLE
Serving Frameworks: text-embeddings

### ISSUE THREAD

**Issue by michaelfeil** [tensorchord/Awesome-LLMOps#107]
thanks for adding this list. I propose to add some of the following links under large-model-serving. In particular, some of the repos are not for decoder models, but more for sentence transformers or clip.

# Embeddings from OpenAI clip.
Jina
https://github.com/jina-ai/clip-as-service (Apache)

# Text-embeddings:
My own project: infinity ( just add it if you like it)
https://github.com/michaelfeil/infinity (MIT)
https://github.com/huggingface/text-embeddings-inference (no opensource Licence)

# LLM Inference as a service:

Huggingface/ TGI
https://github.com/huggingface/text-generation-inference (no opensource licence after 1.0)
Nvidia-TensorRTLLM (Apache2.0)

**Comment by NeroHin** [comment]
Hello @michaelfeil! Thanks for your suggestion, and please feel free to create a pull request to add it.
