### ISSUE TITLE
Recommend a LLM bot building repo: Embedchain

### ISSUE THREAD

**Issue by aryankhanna475** [tensorchord/Awesome-LLMOps#88]
Found your compilation list very useful. 
Recently have been using this helpful OpenSource repo to build ChatGPT like bots; it requires very less coding and could help people.

Embedchain: 
https://github.com/embedchain/embedchain

**Comment by aryankhanna475** [comment]
Have tried to address this via this PR: "update: LLM Ops with embedchain #89"

Happy to help contribute to this repo.

**Comment by gaocegege** [comment]
Thanks for your contribution! :tada: :+1:

I merged the PR, am closing this issue.
